name: Test before merging

on: [push, pull_request]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build redeye
      run: docker build -t ghcr.io/redeye-framework/redeye:latest .

    - name: Run redeye
      run: docker-compose up -d

    - name: Check main page
      run: curl http://localhost:8443

    - name: Check APIs
      run: curl localhost:8443/api/servers